# MAIL_SERVER = 'smtp.gmail.com'
# MAIL_PORT = 587
# MAIL_USE_TLS = True
# MAIL_USERNAME = ""
# MAIL_PASSWORD = ""
# MAIL_DEFAULT_SENDER = "" or MAIL_USERNAME
# MAIL_RECEIVER = "" or MAIL_USERNAME